version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"

  coverage:
    desc: "Run tests with coverage and generate an HTML report"
    cmds:
      - go test ./... -coverprofile=.build/coverage.out
      - go tool cover -html=.build/coverage.out -o .build/coverage.html